server:
  port: 8084 # Port where the Spring Boot application will run (default: 8080)

spring:
  devtools:
    restart:
      enabled: false

  session:
    store-type: redis # Store HTTP session data in Redis (for distributed sessions)

  data:
    redis:
      host: ${REDIS_HOST:localhost}   # Redis host (default: localhost)
      port: ${REDIS_PORT:6379}        # Redis port (default: 6379)
      password: ${REDIS_PASSWORD:password} # Redis password (default: password)
      ssl-enabled: false              # Enable SSL for Redis (false for local, true for cloud services like AWS ElastiCache)
      timeout: 60000                  # Connection timeout in milliseconds
      database: 0                     # Redis database index (default: 0)

app:
  defaultRoom: general                # Default chat room
  channelPrefix: demo.chat.           # Prefix for all chat channels
  wildcard: demo.chat.*               # Wildcard pattern for channel subscriptions
  startup:
    replayOnStart: true               # Publish messages.json on application startup
    resource: classpath:data/messages.json # Path to the startup messages JSON file

info:
  application:
    name: '@project.name@'            # Application name from project metadata
    description: '@project.description@' # Application description from project metadata
    version: '@project.version@'      # Application version from project metadata

logging:
  level:
    com.example.redispubsub: DEBUG          # Logging level for application classes
    org.springframework.data.redis: DEBUG   # Logging level for Spring Data Redis
