server:
  port: 8082 # Port where the Spring Boot application will run (default: 8080)

spring:
  session:
    store-type: redis # Store HTTP session data in Redis (for distributed sessions)

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST:localhost} # Redis host (default: localhost if not set)
      port: ${REDIS_PORT:6379}      # Redis port (default: 6379 if not set)
      password: ${REDIS_PASSWORD:password}  # Redis password (default: 'password' if not set)
      ssl-enabled: true            # SSL connection for Redis (true for security)
      timeout: 30000                # Redis connection timeout in milliseconds (reduced for security)
      database: 0                   # Redis database (default is 0)
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  security:
    enabled: true

info:
  application:
    name: '@project.name@'        # Application name from project metadata
    description: '@project.description@' # Application description from project metadata
    version: '@project.version@'  # Application version from project metadata

logging:
  level:
    com.example.redispubsub: DEBUG
    org.springframework.data.redis: DEBUG
