server:
  port: 8085 # Port where the Spring Boot application will run (default: 8080)

spring:
  session:
    store-type: redis # Store HTTP session data in Redis (for distributed sessions)

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST:localhost} # Redis host (default: localhost if not set)
      port: ${REDIS_PORT:6379}      # Redis port (default: 6379 if not set)
      password: ${REDIS_PASSWORD:password}  # Redis password (default: 'password' if not set)
      ssl-enabled: false            # SSL connection for Redis (false for local setups, true for cloud like AWS ElastiCache)
      timeout: 2000ms                # Redis connection timeout in milliseconds (updated to 2000ms)
      database: 0                   # Redis database (default is 0)

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false

info:
  application:
    name: '@project.name@'        # Application name from project metadata
    description: '@project.description@' # Application description from project metadata
    version: '@project.version@'  # Application version from project metadata

logging:
  level:
    com.example.redispubsub: DEBUG
    org.springframework.data.redis: DEBUG
